#!/usr/bin/python3
'''
Code entry to run the scow-sync
'''
from argsparser import StartArgsParser
from scowsync import ScowSync

# ok for file transfer
if __name__ == '__main__':
    parser = StartArgsParser()
    args = parser.get_args_parser().parse_args()
    scow = ScowSync(args.address, args.user, args.source, args.destination,
                    args.max_depth, args.port, args.sshkey_path)
    scow.transfer_files()
