#!/usr/bin/python3
'''
query the progress of file transfered
'''
import os
import json
import codecs
import sys


def process_file(file_path):
    '''
    parse the last line and concat
    '''
    with codecs.open(file_path, 'r', encoding='utf-8') as file_stream:
        last_line = ''
        for line in file_stream:
            last_line = line
        if last_line != '':
            json_obj = json.loads(last_line)
            return json_obj
        else:
            return None

def traverse_folder(folder_path):
    '''
    traverse /tmp/scow-sync
    '''
    progresses = []
    for root, dirs, files in os.walk(folder_path):
        for dir in dirs:
            transfer_id = os.path.join(root, dir)
            for file in os.listdir(transfer_id):
                file_path = os.path.join(transfer_id, file)
                progress = process_file(file_path)
                if progress:
                    progresses.append(progress)
    return progresses


if __name__ == '__main__':

    TRANSFER_PATH = '/tmp/scow-sync'

    progress = traverse_folder(TRANSFER_PATH)
    sys.stdout.write(json.dumps(traverse_folder(TRANSFER_PATH)))
    sys.stdout.flush()

    sys.exit()
