#!/usr/bin/python3
'''
query the progress of file transfered
'''
import json
import os
import sys
from subprocess import PIPE, CalledProcessError, Popen

def process_file(file_path):
    '''
    parse the output of rsync
    '''
    if os.path.exists(file_path):
        try:
            tail_progress = Popen(['tail', '-n', '2', file_path], stdout=PIPE, stderr=PIPE)
            stdout, stderr = tail_progress.communicate()
            
            sys.stderr.write(stderr.decode('utf-8'))
            sys.stderr.flush()

            # stdout: filename\n\r xxx \r xxx \r xxx \r
            if stdout != '':
                lines =  stdout.decode('utf-8')
                if '%' not in lines: # 还没开始打印进度
                    return None
                
                lines_list = lines.split('\n')

                filename = lines_list[0]
                
                ## DEBUG
                # progess_list = lines_list[1].split('\r')
 
                # progress_line = progess_list[-1]

                # progress_parts = progress_line.split()

                progress_parts = lines_list[1].split('\r')[-1].split()
                transfer_size = progress_parts[0]
                progress = progress_parts[1]
                speed = progress_parts[2]
                time = progress_parts[3]
                return {"filename": filename, 'transfer_size': transfer_size, 'progress': progress, 'speed': speed, 'time': time}
            else:
                return None
        except CalledProcessError:
            return None
        
def traverse_folder(folder_path):
    '''
    traverse ~/scow/.scow-sync
    '''
    progresses = []
    for root, dirs, files in os.walk(folder_path):
        for dir in dirs:
            transfer_id = os.path.join(root, dir)
            for file in os.listdir(transfer_id):
                file_path = os.path.join(transfer_id, file)
                progress = process_file(file_path)
                if progress:
                    progresses.append(progress)
    return progresses


if __name__ == '__main__':

    TRANSFER_PATH = os.path.expanduser('~/scow/.scow-sync')

    progress = traverse_folder(TRANSFER_PATH)
    sys.stdout.write(json.dumps(traverse_folder(TRANSFER_PATH)))
    sys.stdout.flush()

    sys.exit()
