#!/usr/bin/python3
'''
Start a file transfer asynchronously
'''
import os
import sys
from subprocess import Popen
import utils
from argsparser import ArgsParser

if __name__ == '__main__':
    args = ArgsParser().get_args_parser().parse_args()
    cmd = f'scow-sync -a {args.address} -u {args.user} -s {args.source} -d {args.destination} -m {args.max_depth} -p {args.port} -k {args.sshkey_path}'
    raw_string = f'{args.address} {args.user} {args.source} {args.destination}'
    unique_id = utils.gen_file_transfer_id(raw_string)

    if not os.path.exists(os.path.join('/tmp/scow-sync', str(unique_id))):
        os.mkdir(os.path.join('/tmp/scow-sync', str(unique_id)), 0o777)

            
    popen = Popen(cmd, shell=True, stdout=open('/tmp/scow-sync/scow-sync.out','a',encoding='utf-8'), stderr=open('/tmp/scow-sync/scow-sync.err','a',encoding='utf-8'))

    sys.exit()
