#!/usr/bin/python3
'''
Kill a file transfer
'''
# pylint: disable=C0103
import sys
import os
import signal
from subprocess import Popen
import psutil
from utils import args_parser, gen_file_transfer_id
import config

def __parse_cmdline(cmdline):
    '''
    从命令中解析出[user, address, src_path, dst_path, exclude]
    '''
    info = {'user': '', 'address': '', 'src_path': '', 'dst_path': '', 'exclude': ''}

    for index in range(len(cmdline)):
        content = cmdline[index]
        # 解析 user@address:dst_path
        if '@' in content and ':' in content:
            # 先拆分 '@'，然后检查拆分后的列表长度是否足够
            user_address = content.split('@')
            if len(user_address) > 1:
                info['user'] = user_address[0]
                address_path = user_address[1].split(':')
                if len(address_path) > 1:
                    info['address'] = address_path[0]
                    info['dst_path'] = address_path[1]
                else:
                    sys.stderr.write(f"Error: Incomplete address or path in content: {content}\n")
                    sys.stderr.flush()
            else:
                sys.stderr.write(f"Error: Invalid user@address format in content: {content}\n")
                sys.stderr.flush()

            # 解析 src_path，即 user@address:dst_path 的前面一个参数
            if index - 1 >= 0:  # 确保 index-1 不会导致负索引访问错误
                info['src_path'] = cmdline[index - 1]

        # 解析 exclude
        if content == '--exclude':
            if index + 1 < len(cmdline):  # 确保 index+1 不会超出列表范围
                info['exclude'] += f'{cmdline[index + 1]} '
            else:
                sys.stderr.write("Error: --exclude option provided without a following path.\n")
                sys.stderr.flush()

    return info



def find_process(filepath: str, address: str, user: str):
    '''
    找到对应的rsync进程。对于一个采用ssh协议传输的rsync进程，其结构通常是:
    1  |——/bin sh -c rsync
    2   |——rsync
    3    |——ssh
    需要关闭的是
    @return: (进程, 解析后的cmd列表, cmd原始str)
    '''
    rsync_process = None
    cmd_info = None
    cmd_raw = None
    for process in psutil.process_iter():
        cmdline = process.cmdline()
        if len(cmdline) == 0 or cmdline[0] != 'rsync':
            continue
        else:
            # 检查address, user, src_path是否对的上
            cmd_info = __parse_cmdline(cmdline)
            if cmd_info['user'] == user and \
                    cmd_info['address'] == address and \
                    cmd_info['src_path'] in filepath:  # 注意，这个地方是子集
                rsync_process = process
                # cmd_raw需要做进一步处理，因为rsync子进程中的ssh -p xx -i xx -o xx 没有加引号需要加引号
                for i, element in enumerate(cmdline):
                    context = element
                    if context == '-e':
                        if i + 1 < len(cmdline):  # 检查 i + 1 是否超出范围
                            cmdline[i + 1] = f"\'{cmdline[i + 1]}\'"
                        else:
                            sys.stderr.write("Error: -e option provided without a following command.\n")
                            sys.stderr.flush()
                            continue
                break
            continue
    return rsync_process, cmd_info, cmd_raw


def __restart_rsync(transfer_id, cmd, cmd_info, error_path):
    '''
    重启 rsync 进程
    '''
    output_dir_path = os.path.join(config.OUTPUT_PATH, str(transfer_id))

    # 检查并创建输出目录
    if not os.path.exists(output_dir_path):
        try:
            os.mkdir(output_dir_path, 0o700)
        except OSError as e:
            sys.stderr.write(f"Error creating directory {output_dir_path}: {e}\n")
            sys.stderr.flush()
            return  # 如果无法创建目录，则终止函数

    output_file_path = os.path.join(output_dir_path, os.path.basename(f"{cmd_info['src_path']}.out"))

    try:
        with open(output_file_path, 'a', encoding='utf-8') as file_stream:
            # 第一行是关于接收集群和文件（文件夹）父路径的信息
            file_stream.write(f"{cmd_info['address']} {os.path.dirname(cmd_info['src_path'])}\n")
    except IOError as e:
        sys.stderr.write(f"Error opening file {output_file_path} for writing: {e}\n")
        sys.stderr.flush()
        return  # 如果无法打开文件，则终止函数

    # 准备执行 rsync 命令，并确保在成功后删除中间文件
    exe_cmd = f'{cmd} && rm -rf {output_dir_path}'

    try:
        # 启动 rsync 进程
        Popen(
            exe_cmd,
            stdout=open(output_file_path, 'a', encoding='utf-8'),
            stderr=open(error_path, 'a', encoding='utf-8'),
            universal_newlines=True,
            shell=True
        )
    except Exception as e:
        sys.stderr.write(f"Error starting rsync process: {e}\n")
        sys.stderr.flush()
        return  # 如果进程启动失败，则终止函数


def close_process_by_filepath(filepath: str, output_path: str, error_path: str, address: str, user: str):
    '''
    关闭命令中含有该文件路径的进程，并根据需要重启 rsync 进程。
    '''
    process, cmd_info, cmd_raw = find_process(filepath, address, user)

    if process is None or cmd_info is None or cmd_raw is None:
        error_message = f'Kill transfer {filepath} error: no process found\n'
        try:
            with open(error_path, 'a', encoding='utf-8') as file_stream:
                file_stream.write(error_message)
        except IOError as e:
            sys.stderr.write(f"Error writing to error log {error_path}: {e}\n")
            sys.stderr.flush()

        sys.stderr.write(error_message)
        sys.stderr.flush()
        sys.exit(-1)
    else:
        try:
            process.send_signal(signal.SIGINT)  # 发送 SIGINT 信号终止进程
        except psutil.NoSuchProcess:
            error_message = f'Error: process {process.pid} does not exist.\n'
            try:
                with open(error_path, 'a', encoding='utf-8') as file_stream:
                    file_stream.write(error_message)
            except IOError as e:
                sys.stderr.write(f"Error writing to error log {error_path}: {e}\n")
                sys.stderr.flush()

            sys.stderr.write(error_message)
            sys.stderr.flush()
            return
        except Exception as e:
            error_message = f'Error sending signal to process {process.pid}: {e}\n'
            try:
                with open(error_path, 'a', encoding='utf-8') as file_stream:
                    file_stream.write(error_message)
            except IOError as e:
                sys.stderr.write(f"Error writing to error log {error_path}: {e}\n")
                sys.stderr.flush()

            sys.stderr.write(error_message)
            sys.stderr.flush()
            return

        # 成功终止进程后记录日志
        success_message = f'Kill transfer {filepath} completed\n'
        try:
            with open(output_path, 'a', encoding='utf-8') as file_stream:
                file_stream.write(success_message)
        except IOError as e:
            sys.stderr.write(f"Error writing to output log {output_path}: {e}\n")
            sys.stderr.flush()

        # 判断需不需要重启 rsync 进程
        if cmd_info['src_path'] == filepath:
            # 如果取消的进程只负责传输该单个文件，不需要重启
            return
        else:
            # 在 rsync 规则中，需要将相对路径加入到 exclude 中
            relative_path = os.path.relpath(path=filepath, start=cmd_info['src_path'])

            # 生成唯一的 transfer_id
            raw_string = f"{cmd_info['address']} {cmd_info['user']} {cmd_info['src_path']} {cmd_info['dst_path']} --exclude {cmd_info['exclude']} {relative_path}"
            transfer_id = gen_file_transfer_id(raw_string)

            # 重启 rsync 进程并排除指定的文件
            __restart_rsync(transfer_id, cmd_raw + " --exclude=" + relative_path, cmd_info, error_path)

    return



if __name__ == '__main__':

    # 获取参数
    args = args_parser.terminate_args_parse()

    # 停止进程
    close_process_by_filepath(
        args.source, config.LOG_PATH, config.ERROR_PATH, args.address, args.user)

    sys.exit()
